---
- name: Reconfigure Timezone To UTC
  community.general.timezone: 
    name: "UTC"
  become: yes

- name: Change "/opt" Ownership
  tags: ['base']
  ansible.builtin.file:
    path: "/opt"
    state: directory
    recurse: true
    mode: 0700
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
  become: yes

- name: Creating Additional Home Directorys
  tags: ['base']
  ansible.builtin.file:
    path: "/home/{{ r_uid }}/{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
  become: no
  with_items:
    - "{{ r_home_dirs }}"

- name: Transfer Files To Kali.
  tags: ['base']
  ansible.builtin.copy:
    src:  "{{ item }}"
    dest: "/home/{{ r_uid }}/{{ item }}"
    mode: 0600
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
  become: no
  with_items: 
    - "{{ r_home_files }}"

- name: Transfer .z* Files To Home
  tags: ['base']
  ansible.builtin.template:
    src: "templates/{{ item }}.j2" 
    dest: "/home/{{ r_uid }}/{{ item }}"
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
    mode: '0600' 
  become: no
  with_items:
    - "{{ r_z_files }}"

- name: Remove Unwanted Packages
  tags: ['base']
  ansible.builtin.apt:
    name: "{{ r_packages_remove|default([]) }}"
    force: yes
    purge: yes
    state: absent
  become: yes

- name: Update Packages
  tags: ['base']
  ansible.builtin.apt:
    update_cache: yes
    only_upgrade: true
  become: yes

- name: Install Common Packages
  tags: ['base']
  ansible.builtin.apt:
    name: "{{ r_packages|default([]) }}"
    update_cache: yes
    install-recommends: no
    state: present
    autoremove: yes
  become: yes

- name: Start Services
  tags: ['base']
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  become: yes
  with_items:
    - "{{ r_services }}"
  
- name: Initialise Metasploit
  tags: ['base']
  ansible.builtin.command:
    cmd: "msfdb init"
    creates: "/usr/share/metasploit-framework/config/database.yml"
