---
- name: Reconfigure Timezone To UTC
  community.general.timezone: 
    name: "UTC"

- name: Creating additional directorys
  tags: ['base']
  ansible.builtin.file:
    path: "/home/{{ r_uid }}/{{ item }}"
    state: directory
    mode: 0700
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
  loop:
    - "Tools"
    - "Reports"
    - "bin"
    - "vpn"
    - "wordlists"

- name: Transfer Files To Kali.
  tags: ['base']
  ansible.builtin.copy:
    src:  "{{ item }}"
    dest: "/home/{{ r_uid }}/{{ item }}"
    mode: 0600
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
  with_items:
    - .zshrc
    - .vimrc
    - .tmux.conf
    - .config/qterminal.org/qterminal.ini

- name: Transfer .zdirs File To $HOMEDIR
  tags: ['base']
  ansible.builtin.template:
    src: templates/.zdirs.j2
    dest: "/home/{{ r_uid }}/.zdirs"
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
    mode: '0600' 

- name: Transfer .zprofile File To $HOMEDIR
  tags: ['base']
  ansible.builtin.template:
    src: templates/.zprofile.j2
    dest: "/home/{{ r_uid }}/.zprofile"
    owner: "{{ r_uid }}"
    group: "{{ r_gid }}"
    mode: '0600' 

- name: Remove Unwanted Packages
  tags: ['base']
  ansible.builtin.apt:
    name: "{{ r_packages_remove|default([]) }}"
    force: yes
    purge: yes
    state: absent
  become: yes

- name: Update Packages
  tags: ['base']
  ansible.builtin.apt:
    update_cache: yes
    only_upgrade: true
  become: yes

- name: Install Common Packages
  tags: ['base']
  ansible.builtin.apt:
    name: "{{ r_packages|default([]) }}"
    update_cache: yes
    install-recommends: no
    state: present
    autoremove: yes
  become: yes

- name: Start Services
  tags: ['base']
  block:
    - name: Enable PostGreSQL Service
      ansible.builtin.service:
        name: postgresql
        enabled: yes

    - name: Start PostGreSQL Service
      ansible.builtin.service:
        name: postgresql
        state: started
  
- name: Initialise Metasploit
  tags: ['base']
  ansible.builtin.command:
    cmd: "msfdb init"
    creates: "/usr/share/metasploit-framework/config/database.yml"

- name: Check Ghidra Installed Or Not
  tags: ['base']
  ansible.builtin.stat:
    path: "/opt/ghidra"
    get_checksum: no
  register: ghidra_dir

- name: Download & Install Ghidra
  tags: ['base']
  block:
    - name: Download Ghidra
      ansible.builtin.get_url:
        url: "{{ r_ghidra_url }}"
        dest: "/opt/"
        
    - name: Unzip Ghidra
      ansible.builtin.command:
        cmd: "unzip -d /opt/ghidra /opt/{{ r_ghidra_zip }}"
    
    - name: Change Permissions
      ansible.builtin.command:
        cmd: "chown -R {{ r_uid }}:{{ r_gid }} /opt/ghidra"

    - name: Remove Ghidra Download
      ansible.builtin.file:
        path: "/opt/{{ r_ghidra_zip }}"
        state: absent
  when: not ghidra_dir.stat.exists
