---
apps:
  ghidra:
    url: 'https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_10.2.2_build/ghidra_10.2.2_PUBLIC_20221115.zip'
    dest: '/opt/ide' 
    is_present: '/opt/ide/ghidra_10.2.2_PUBLIC'
  cyberchef:
    url: 'https://gchq.github.io/CyberChef/CyberChef_v9.55.0.zip'
    dest: '/opt/cyberchef'
    is_present: '/opt/cyberchef/ChefWorker.js.LICENSE.txt'
